// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC0dSxDujft8WflGmS3d0Xq1g5V0kHhdE',
    appId: '1:755785009601:android:95c60dcf121a212d614740',
    messagingSenderId: '755785009601',
    projectId: 'petromind-3b8b2',
    storageBucket: 'petromind-3b8b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8DluqZCC8usEEIGBpxHIdYwlx8_pw9p4',
    appId: '1:755785009601:ios:0623cbe2b5739f95614740',
    messagingSenderId: '755785009601',
    projectId: 'petromind-3b8b2',
    storageBucket: 'petromind-3b8b2.firebasestorage.app',
    iosBundleId: 'com.petromind.petromind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8DluqZCC8usEEIGBpxHIdYwlx8_pw9p4',
    appId: '1:755785009601:ios:0623cbe2b5739f95614740',
    messagingSenderId: '755785009601',
    projectId: 'petromind-3b8b2',
    storageBucket: 'petromind-3b8b2.firebasestorage.app',
    iosBundleId: 'com.petromind.petromind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVcMLgCJqKn5myainXP_xfXtWTL-R9d4o',
    appId: '1:755785009601:web:f3945bb3fbe7dc79614740',
    messagingSenderId: '755785009601',
    projectId: 'petromind-3b8b2',
    authDomain: 'petromind-3b8b2.firebaseapp.com',
    storageBucket: 'petromind-3b8b2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVcMLgCJqKn5myainXP_xfXtWTL-R9d4o',
    appId: '1:755785009601:web:f3945bb3fbe7dc79614740',
    messagingSenderId: '755785009601',
    projectId: 'petromind-3b8b2',
    authDomain: 'petromind-3b8b2.firebaseapp.com',
    storageBucket: 'petromind-3b8b2.firebasestorage.app',
  );

}